version: "3.7"

networks:
  feedom:
    driver: bridge

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: unless-stopped
    volumes:
    - $PWD/client.json:/etc/v2ray/config.json
    expose:
    - 1080
    - 8080
    ports:
    - 127.0.0.1:1080:1080
    - 127.0.0.1:8080:8080
    networks:
    - feedom
