version: "3.7"

volumes:
  caddy_data:
  caddy_config:

networks:
  feedom:
    driver: bridge

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    container_name: caddy
    ports:
    - "443:443"
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config
    networks:
    - feedom
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: unless-stopped
    volumes:
    - $PWD/server.json:/etc/v2ray/config.json
    expose:
    - 9988
    networks:
    - feedom